robot:
  base_name: fishbot_v2_3d
  # frames
  base_frame: base_link
  lidar_frame: lidar_link
  imu_frame: imu_link
  # topics
  odom_pub: wheel_odom
  lidar_pub: lidar_points
  imu_pub: imu

geometry:
  base:
    cyl_radius: 0.10
    cyl_length: 0.12
    mass: 0.2
    inertia:
      ixx: 0.0122666
      iyy: 0.0122666
      izz: 0.02
  wheel:
    radius: 0.0325
    length: 0.04
    mass: 0.2
    inertia_diag: 0.000190416666667
  caster:
    radius: 0.016
    mass: 0.02

kinematics:
  wheel_separation: 0.20
  wheel_diameter: 0.065

plugins:
  diff_drive:
    update_rate: 30
    max_wheel_torque: 20.0
    max_wheel_accel: 1.0
    publish_odom: true
    publish_odom_tf: false
    publish_wheel_tf: false

imu:
  update_rate: 100
  visualize: true
  noise:
    ang_stddev: 2e-4
    ang_bias_mean: 7.5e-6
    ang_bias_stddev: 8e-7
    lin_stddev: 1.7e-2
    lin_bias_mean: 0.1
    lin_bias_stddev: 0.001

lidar:
  update_rate: 10
  visualize: false
  h_rays:
    samples: 360
    min_angle: -3.14159
    max_angle: 3.14159
    resolution: 0.5
  v_rays:
    samples: 16
    min_angle: -0.223599
    max_angle: 0.561799
    resolution: 0.5
  range_min: 0.12
  range_max: 20.0
  range_res: 0.01
  noise_stddev: 0.01
